name: build-tictactoe
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Step1 - Checkout to TAG xxxx
        uses: actions/checkout@v4

      - name: Step2 - Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Step3 - Build the docker image
        run: docker build -f Dockerfile -t mushroomgead/vite-tictactoe:$TAG_NAME .

      - name: Step4 - Push the Docker image
        run: docker push mushroomgead/vite-tictactoe:$TAG_NAME
