name: build  tictactoe
on:
  push:
    tags:
      - "v.*.*"

env:
  TAG_NAME: ${{github.ref_name}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Step1 - Checkout to TAG $TAG_NAME
        uses: actions/checkout@v4

      - name: Step2 - Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Step3 - Build the docker image
        run: docker build . -- file Dockerfile --tag mushroomgead/vite-tictactoe:$TAG_NAME

      - name: Step4 - Push the Docker image
        run: docker push mushroomgead/vite-tictactoe:$TAG_NAME
